### ISSUE TITLE
Issue in using ngx-logger in an angular library (buildable)

### ISSUE THREAD

**Issue by hmendezm** [dbfannin/ngx-logger#298]
Hi guys,
I am trying to use ngx-logger in my buildable library but I got the error below
core.mjs:6500 ERROR NullInjectorError: R3InjectorError(AppModule)[TestService -> TestService -> TestService -> NGXLogger]: 
  NullInjectorError: No provider for NGXLogger!

### app/module

```
@NgModule({
....
  imports: [
    BrowserModule,
    HttpClientModule,
    LoggerModule.forRoot({
      level: NgxLoggerLevel.DEBUG,
      timestampFormat: 'HH:mm:ss.SSS',
      serverLogLevel: NgxLoggerLevel.ERROR,
      disableConsoleLogging: false
    })]
})
export class AppModule { }
```

### library module
```
@NgModule({
  imports: [CommonModule, LoggerModule.forChild()]
})
export class ReusableModule {}
```

**Comment by bmtheo** [comment]
Do you build the library by itself or with the app ?

**Comment by hmendezm** [comment]
Hi bmtheo,

I build the library with the app

**Comment by bmtheo** [comment]
Ok I tried in the project with the same setup (app.module with LoggerModule.forRoot and another module with LoggerModule.forChild) and it works fine

We probably have something different, can you provide a reproduction repo so that I can look into that ?

**Comment by hmendezm** [comment]
Ok. I will create a simple app and reproduce the problem

**Comment by hmendezm** [comment]
I could not reproduce in a new project. it looks like is a real project that has config problems and I do not know where.
this is the full error that I get

bootstrap.ts:13 NullInjectorError: R3InjectorError(AppModule)[EffectsRootModule -> InjectionToken @ngrx/effects Root Effects -> AuthenticationEffects -> AuthenticationService -> StateService -> FormService -> FormService -> FormService -> LoggerService -> NGXLogger]: 
  NullInjectorError: No provider for NGXLogger!
    at NullInjector.get (core.mjs:11135:27)
    at R3Injector.get (core.mjs:11302:33)
    at injectInjectorOnly (core.mjs:4786:33)
    at Module.ɵɵinject (core.mjs:4790:12)
    at Object.LoggerService_Factory [as factory] (logger.service.ts:8:27)
    at R3Injector.hydrate (core.mjs:11472:35)
    at R3Injector.get (core.mjs:11291:33)
    at injectInjectorOnly (core.mjs:4786:33)
    at Module.ɵɵinject (core.mjs:4790:12)
    at Object.FormService_Factory [as factory] (form.service.ts:94:25)

**Comment by egandro** [comment]
@hmendezm works for me with MEF
